function qscomp_writereport(strFileName,casData);

% Writes a csv from data generated by qscomp_overview
% $Id: qscomp_writereport.m 4160 2009-12-11 19:10:14Z khrovat $ %

fid = fopen(strFileName,'w');
fprintf(fid,'Rack,Min Mag,Mean Mag,Max Mag,Min Perp,Mean Perp,Max Perp,OrbAvgX,OrbAvgY,OrbAvgZ,UnitX,UnitY,UnitZ\n');

for i = 1:length(casData)
   strRackName = casData{i}{1};
   mag = casData{i}{2}*1e6;
   perpmag = casData{i}{3}*1e6;
   orbavg = casData{i}{4}*1e6;
   Uavg = casData{i}{5};
   
filerow = fprintf(fid,'%s,%7.2f,%7.2f,%7.2f,%7.2f,%7.2f,%7.2f,%7.2f,%7.2f,%7.2f,%7.2f,%7.2f,%7.2f\n',...
     strRackName,mag,perpmag,orbavg,Uavg); 
end

fclose(fid);